### ISSUE TITLE
'Reduce unused JavaScript' suggestions?

### ISSUE THREAD

**Issue by InstantlyMoist** [johannschopplich/nuxt-gtag#57]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.19.1
- Nuxt Version:     -
- CLI Version:      3.11.1
- Nitro Version:    -
- Package Manager:  unknown
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

Running within Docker

### Reproduction

Currently none, installed nuxt-gtag and added to the module

### Describe the bug

![image](https://github.com/johannschopplich/nuxt-gtag/assets/32609460/7087829b-51b8-4978-80e5-b5ec6425ec18)

Currently this shows up in lighthouse as 'Unused JavaScript', while the loadingStrategy is set to 'defer', with 'async' we're getting the same issue.

Is there any way to prevent this, as it's pulling our performance score down on mobile. Thanks!

**Comment by johannschopplich** [comment]
Thanks for the report. Sorry, but there's nothing this library can do, except if you use a cookie banner and let the user opt-in to tracking – then, the `gtag.js` library is loaded later during the lifecycle of your app.

This Nuxt module merely loads Google's `gtag.js` library and adds some configuration options. Thus, the Lighthouse issue originates in Google's own library size. The Google crawler waits until all scripts are loaded, that's why `defer` and `async` behave the same in your case.

Closing this, due not connected to this module.
